#version 450 core

#ifndef DEFINES_H
#include "../include/defines.h"
#endif//DEFINES_H

#ifndef SHADER_INCLUDES_GLSL
#include "shader_includes.glsl"
#endif//SHADER_INCLUDES_GLSL

const float S = 0.08;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    ivec2 index = ivec2(gl_GlobalInvocationID.xy);
    float v = imageLoad(map_in, index).r;
    imageStore(map_out, index, vec4((v - S) * float(0.0 < v)));
}