#ifndef DEFINES_H
#define DEFINES_H

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define MAP_WIDTH (WINDOW_WIDTH / 1)
#define MAP_HEIGHT (WINDOW_HEIGHT / 1)
#define NUM_UNIFORMS 3
#define NUM_ANTS 10000
#define NUM_COMP_SHADERS 2

#define SIZE_UNIFORM_INDEX 0
#define MAP_SIZE_INDEX 1
#define TIME_UNIFORM_INDEX 2

#define UNIVERSE_SIZE 1e8
#define GRAVITATIONAL_CONSTANT 6.67E-11
#define EPSILON 1E4
#define TREE_EPSILON 0.0001

#define MACRO_SQUARED_DIST(a, b) ((a) * (a) + (b) * (b))

#endif // DEFINES_H
